In [1]:
!pip install numpy


In [2]:
import numpy

In [3]:
lista = [1,2,3]

In [4]:
type(lista)

list

In [5]:
matriz = numpy.array(lista)

In [7]:
type(matriz)

numpy.ndarray

In [8]:
matriz

array([1, 2, 3])

In [9]:
import numpy as np

In [11]:
matriz2 = np.array(lista)

In [12]:
matriz2

array([1, 2, 3])

In [13]:
matriz.ndim

1

In [14]:
matriz.shape

(3,)

In [15]:
lista3 = [1.0,True,"a",3]

In [16]:
matriz3 = np.array(lista3)

In [19]:
matriz3
#Aunque la lista tiene elementos de diferente tipo de datos, el arreglo los transforma a un solo tipo
#en este caso todos se convirtieron a tipo caracter

array(['1.0', 'True', 'a', '3'], dtype='<U32')

In [20]:
print(matriz3.dtype)

<U32


In [21]:
print(matriz2.dtype)

int32


## Matrices solo pueden tener un tipo de dato

In [24]:
matriz4 = np.array([1,2,3], dtype="float")

In [26]:
matriz4

array([1., 2., 3.])

In [27]:
matriz5 = np.array([1,2,3], dtype="float16")

In [28]:
matriz5.dtype

dtype('float16')

In [29]:
m=[1,2,3]
n=[3,4,5]


In [30]:
m+n

[1, 2, 3, 3, 4, 5]

In [31]:
matriz_m = np.array(m)
matriz_n = np.array(n)

In [32]:
matriz_m + matriz_n

array([4, 6, 8])

In [33]:
np.square(matriz_m)

array([1, 4, 9], dtype=int32)

In [34]:
matriz_m[0]

1

In [35]:
matriz_m[-1]

3

In [36]:
matriz_m[-3]

1

In [44]:
matriz_m[1] = True

In [45]:
matriz_m

array([1, 1, 3])

In [40]:
matriz_m[0]="abc"

ValueError: invalid literal for int() with base 10: 'abc'

In [41]:
matriz_o = np.array([6,7,8,9])

In [42]:
matriz_m

array([1, 2, 3])

In [43]:
matriz_m + matriz_o

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [47]:
matriz_negativos = matriz_m - matriz_n

In [48]:
np.absolute(matriz_negativos)

array([2, 3, 2])

In [49]:
np.maximum(matriz_m,matriz_n)

array([3, 4, 5])

In [50]:
np.minimum(matriz_m,matriz_n)

array([1, 1, 3])

In [51]:
np.maximum(matriz_m,matriz_o)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [52]:
desordenada=np.array([5,21,8,2,77,38,-90])

In [54]:
desordenada.sort()
desordenada

array([-90,   2,   5,   8,  21,  38,  77])

In [55]:
matriz_1 = np.array(range(1,6))
matriz_2 = np.array(range(4,11))

matriz_1

In [56]:
matriz_1

array([1, 2, 3, 4, 5])

In [57]:
matriz_2

array([ 4,  5,  6,  7,  8,  9, 10])

In [60]:
matriz_append = np.append(matriz_1,matriz_2,axis=0)

In [62]:
np.insert(matriz_append,2,11)

array([ 1,  2, 11,  3,  4,  5,  4,  5,  6,  7,  8,  9, 10])

In [63]:
matriz_append

array([ 1,  2,  3,  4,  5,  4,  5,  6,  7,  8,  9, 10])

# ACTIVIDAD 1

In [79]:
vector = np.array(range(3,41))
vector

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [72]:
arreglo = np.array([0,1,2,3,4,0,1,2,3,4])
arreglo

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [73]:
arreglo.sort()
arreglo

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])